services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    env_file:
      - server/.env
  server_nestjs:
    container_name: server_nestjs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - server/.env
    environment:
      DB_HOST: postgres
  web_nextjs:
    container_name: web_nextjs
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - server_nestjs
    environment:
      - NEXT_PUBLIC_BASE_URL=http://server_nestjs:3000

volumes:
  postgres-data:
