services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    env_file:
      - server/.env
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    env_file:
      - server/.env
    environment:
      DB_HOST: postgres
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_BASE_URL: "http://server:${PORT}"
    ports:
      - "3005:3005"
    depends_on:
      - server

volumes:
  postgres-data:
